/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PChip: typeof import('primevue/chip')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PImage: typeof import('primevue/image')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PRating: typeof import('primevue/rating')['default']
    PSelect: typeof import('primevue/select')['default']
    PSelectButton: typeof import('primevue/selectbutton')['default']
    PSplitButton: typeof import('primevue/splitbutton')['default']
    PTag: typeof import('primevue/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
