/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PChip: typeof import('primevue/chip')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PImage: typeof import('primevue/image')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    POverlayPanel: typeof import('primevue/overlaypanel')['default']
    PRating: typeof import('primevue/rating')['default']
    PSelect: typeof import('primevue/select')['default']
    PSelectButton: typeof import('primevue/selectbutton')['default']
    PTabPanel: typeof import('primevue/tabpanel')['default']
    PTabView: typeof import('primevue/tabview')['default']
    PTag: typeof import('primevue/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
